package com.difft.android.chat.invite

import android.graphics.Bitmap
import android.graphics.Color
import androidx.camera.core.ImageProxy
import com.difft.android.chat.qr.QrEncoder
import com.google.zxing.PlanarYUVLuminanceSource
import io.mockk.every
import io.mockk.mockk
import io.mockk.verify
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import org.robolectric.annotation.GraphicsMode
import java.nio.ByteBuffer

/**
 * Unit tests for [QrCodeAnalyzer] (design §7 T13–T16) plus framework-assumption tests T-A1/T-A2.
 *
 * A fake [ImageProxy] (MockK) supplies a Y-plane luma buffer derived from a REAL QR generated by
 * [QrEncoder], decoded by a REAL [com.difft.android.chat.qr.QrDecoder] (the analyzer owns one). This
 * exercises the genuine frame→source→decode bridge, the one-shot latch, and the mandatory
 * `image.close()` on every path.
 *
 * [GraphicsMode.Mode.NATIVE] so `getPixels` over the generated bitmap reads real composited pixels.
 */
@RunWith(RobolectricTestRunner::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
@Config(sdk = [28])
class QrCodeAnalyzerTest {

    /**
     * Builds a Y-plane luma buffer for [bmp] with the given [rowStride] (>= width for padding tests).
     * Black QR module → luma 0, white → 255 (matches the camera's grayscale Y for a black/white QR).
     */
    private fun lumaBuffer(bmp: Bitmap, rowStride: Int): ByteArray {
        val w = bmp.width
        val h = bmp.height
        val data = ByteArray(rowStride * h)
        val pixels = IntArray(w * h)
        bmp.getPixels(pixels, 0, w, 0, 0, w, h)
        for (y in 0 until h) {
            for (x in 0 until w) {
                // Standard luma; black=0, white=255. QR pixels are pure black/white.
                val argb = pixels[y * w + x]
                val luma = (0.299 * Color.red(argb) + 0.587 * Color.green(argb) + 0.114 * Color.blue(argb)).toInt()
                data[y * rowStride + x] = luma.toByte()
            }
            // Row padding bytes (x in width until rowStride) left as 0 — must NOT corrupt decode.
        }
        return data
    }

    /** A fake ImageProxy whose single Y-plane returns [luma] at [rowStride], sized [w]×[h]. */
    private fun fakeImageProxy(luma: ByteArray, rowStride: Int, w: Int, h: Int): ImageProxy {
        val plane = mockk<ImageProxy.PlaneProxy>(relaxed = true)
        every { plane.buffer } returns ByteBuffer.wrap(luma)
        every { plane.rowStride } returns rowStride
        val image = mockk<ImageProxy>(relaxed = true)
        every { image.planes } returns arrayOf(plane)
        every { image.width } returns w
        every { image.height } returns h
        return image
    }

    private fun encode(content: String, size: Int = 512): Bitmap =
        QrEncoder.encode(content, size, Color.BLACK)
            ?: error("encode returned null for content of length ${content.length}")

    // ── T13: happy path — first decodable frame fires onDecoded once and closes the image ──────
    @Test
    fun `T13 - analyze decodes a QR frame, fires onDecoded once and closes the image`() {
        val content = "https://x.test/abc"
        val bmp = encode(content)
        val image = fakeImageProxy(lumaBuffer(bmp, bmp.width), bmp.width, bmp.width, bmp.height)
        val results = mutableListOf<String>()
        val analyzer = QrCodeAnalyzer { results.add(it) }

        analyzer.analyze(image)

        assertEquals(listOf(content), results)
        verify(exactly = 1) { image.close() }
    }

    // ── T14: duplicate-debounce — same frame twice fires onDecoded exactly once ────────────────
    @Test
    fun `T14 - feeding the same decodable frame twice fires onDecoded only once`() {
        val content = "https://x.test/dup"
        val bmp = encode(content)
        val results = mutableListOf<String>()
        val analyzer = QrCodeAnalyzer { results.add(it) }

        val first = fakeImageProxy(lumaBuffer(bmp, bmp.width), bmp.width, bmp.width, bmp.height)
        val second = fakeImageProxy(lumaBuffer(bmp, bmp.width), bmp.width, bmp.width, bmp.height)
        analyzer.analyze(first)
        analyzer.analyze(second)

        assertEquals(listOf(content), results) // exactly one emission
        verify(exactly = 1) { first.close() }
        verify(exactly = 1) { second.close() } // still closed even after the latch is set
    }

    // ── T15: no-QR frame — onDecoded never fires, image still closed, no throw ─────────────────
    @Test
    fun `T15 - a non-QR frame does not fire onDecoded but still closes the image`() {
        val notQr = androidx.core.graphics.createBitmap(256, 256).apply { eraseColor(Color.GRAY) }
        val image = fakeImageProxy(lumaBuffer(notQr, notQr.width), notQr.width, notQr.width, notQr.height)
        var fired = false
        val analyzer = QrCodeAnalyzer { fired = true }

        analyzer.analyze(image)

        assertEquals(false, fired)
        verify(exactly = 1) { image.close() }
    }

    // ── T16: decode-throws hardening — onDecoded not fired, image closed, loop survives ────────
    @Test
    fun `T16 - a malformed frame buffer does not crash and still closes the image`() {
        // rowStride < width: toLumaSource now clamps cropWidth to minOf(width, rowStride) so the source
        // builds without throwing, then decode finds no QR in the all-zero buffer → onDecoded skipped.
        // Either way (clamp-then-no-decode, or any non-NotFound throw on other devices) the analyzer's
        // runCatching keeps the loop alive and the image is still closed.
        val w = 256
        val h = 256
        val rowStride = 128 // < width → exercises the cropWidth clamp
        val image = fakeImageProxy(ByteArray(rowStride * h), rowStride, w, h)
        var fired = false
        val analyzer = QrCodeAnalyzer { fired = true }

        analyzer.analyze(image) // must not throw

        assertEquals(false, fired)
        verify(exactly = 1) { image.close() }
    }

    // ── T16b: buffer shorter than rowStride*height — safeHeight clamp prevents AIOOBE ───────────
    @Test
    fun `T16b - a buffer smaller than rowStride times height does not crash and closes the image`() {
        // Some devices report height H but back the Y-plane with remaining() < rowStride*H (cropped /
        // partial planes). Without the safeHeight clamp ZXing would read past the array (AIOOBE).
        // toLumaSource must clamp dataHeight/cropHeight to data.size / rowStride and never throw.
        val w = 256
        val h = 256
        val rowStride = 256
        val image = fakeImageProxy(ByteArray(rowStride * (h / 2)), rowStride, w, h) // only half the rows
        var fired = false
        val analyzer = QrCodeAnalyzer { fired = true }

        analyzer.analyze(image) // must not throw — safeHeight clamps to the populated rows

        assertEquals(false, fired)
        verify(exactly = 1) { image.close() }
    }

    // ── T16c: rearm() re-enables scanning after a one-shot decode ──────────────────────────────
    @Test
    fun `T16c - rearm re-enables decoding after the one-shot latch fired`() {
        val content = "https://x.test/rearm"
        val bmp = encode(content)
        val results = mutableListOf<String>()
        val analyzer = QrCodeAnalyzer { results.add(it) }

        val first = fakeImageProxy(lumaBuffer(bmp, bmp.width), bmp.width, bmp.width, bmp.height)
        analyzer.analyze(first)
        assertEquals(listOf(content), results) // latched after first decode

        // Without rearm a second decodable frame is dropped (one-shot-per-foreground).
        val dropped = fakeImageProxy(lumaBuffer(bmp, bmp.width), bmp.width, bmp.width, bmp.height)
        analyzer.analyze(dropped)
        assertEquals(listOf(content), results) // still one emission

        // After rearm (a lifecycle onResume edge) the next decodable frame fires again.
        analyzer.rearm()
        val second = fakeImageProxy(lumaBuffer(bmp, bmp.width), bmp.width, bmp.width, bmp.height)
        analyzer.analyze(second)
        assertEquals(listOf(content, content), results)
        verify(exactly = 1) { first.close() }
        verify(exactly = 1) { dropped.close() }
        verify(exactly = 1) { second.close() }
    }

    // ── T-A1: framework assumption — Y-plane rowStride > width (padded) still decodes ──────────
    @Test
    fun `T-A1 - a padded Y-plane with rowStride greater than width decodes correctly`() {
        // The load-bearing CameraX detail: rows are padded to a stride > width. The analyzer must use
        // rowStride (NOT width) as PlanarYUVLuminanceSource dataWidth; using width would garble luma.
        val content = "https://x.test/padded-stride"
        val bmp = encode(content)
        val padding = 48
        val rowStride = bmp.width + padding
        val image = fakeImageProxy(lumaBuffer(bmp, rowStride), rowStride, bmp.width, bmp.height)
        val results = mutableListOf<String>()
        val analyzer = QrCodeAnalyzer { results.add(it) }

        analyzer.analyze(image)

        assertEquals(listOf(content), results)
        verify(exactly = 1) { image.close() }
    }

    // ── T-A2: framework assumption — PlanarYUVLuminanceSource crop within a padded buffer ──────
    @Test
    fun `T-A2 - PlanarYUVLuminanceSource crops the QR out of a larger padded buffer`() {
        // Pins the crop contract the analyzer relies on: the (0,0,width,height) crop must extract the
        // QR even when the backing buffer is wider (padded) than the QR. Build the source exactly the
        // way the analyzer does and decode it directly via a real QrDecoder.
        val content = "crop-contract-payload-1234567890"
        val bmp = encode(content)
        val padding = 32
        val rowStride = bmp.width + padding
        val luma = lumaBuffer(bmp, rowStride)

        val source = PlanarYUVLuminanceSource(
            luma, rowStride, bmp.height, 0, 0, bmp.width, bmp.height, false,
        )
        assertEquals(content, com.difft.android.chat.qr.QrDecoder().decode(source))

        // And confirm a wrong dataWidth (width instead of rowStride) does NOT decode — proving the
        // stride choice is load-bearing, not incidental.
        val wrong = PlanarYUVLuminanceSource(
            luma, bmp.width, bmp.height, 0, 0, bmp.width, bmp.height, false,
        )
        assertNull(com.difft.android.chat.qr.QrDecoder().decode(wrong))
    }
}
